# Generated by Django 5.2.1 on 2025-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_view_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
    ]
