# Generated by Django 5.2.1 on 2025-05-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_basket_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Basket Item'},
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'book')},
        ),
    ]
