# Generated by Django 5.2.1 on 2025-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_basketitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Book Digital File'),
        ),
    ]
