# Generated by Django 5.2.1 on 2025-05-25 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub'])], verbose_name='Book Digital File'),
        ),
    ]
