# Generated by Django 5.2.1 on 2025-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('online_payment', 'Online Payment'), ('chash_on_delivery', 'Cash on Delivery')], default='online_payment', max_length=20),
        ),
    ]
