# Generated by Django 5.2.1 on 2025-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('process', 'Process'), ('success', 'Success'), ('failed', 'Failed')], default='process', max_length=20),
        ),
    ]
