# Generated by Django 5.2.1 on 2025-05-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_basketitem_options_and_more'),
        ('order', '0006_payment_paid_at_payment_ref_number_payment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='book.books'),
        ),
    ]
