# Generated by Django 5.2.1 on 2025-05-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='will_deliver_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
